<?php
/**
 * Template Name: Home page
 *
 * Template for pages
 *
 * @package      responsive_mobile
 * @license      license.txt
 * @copyright    2014 CyberChimps Inc
 * @since        0.0.1
 *
 * Please do not edit this file. This file is part of the responsive_mobile Framework and all modifications
 * should be made in a child theme.
 */

// If this file is called directly, abort.
if ( ! defined( 'WPINC' ) ) {
    die;
}

get_header(); ?>

<div id="content-full" class="content-area">
    <main id="main" class="site-main full-width" role="main">

        <?php if ( have_posts() ) : ?>

            <?php get_template_part( 'template-parts/loop-header' ); ?>

            <?php /* Start the Loop */ ?>
            <?php while ( have_posts() ) : the_post(); ?>

                <?php get_template_part( 'template-parts/content', 'page' ); ?>
                <?php
            $header_bg_1 = image_details(CFS()->get( 'background_image_1' ));
            $header_bg_2 = image_details(CFS()->get( 'background_image_2' ));
            $header_bg_3 = image_details(CFS()->get( 'background_image_3' ));
            $header_bg_4 = image_details(CFS()->get( 'background_image_4' ));

            $header_slider_array = [$header_bg_1, $header_bg_2, $header_bg_3, $header_bg_4];
            ?>
            <div class="main-banner-section">
              <div class="slider">
                  <?php foreach ($header_slider_array as $header_slider) {
                echo '<div class="slide"><img src="'.$header_slider['url'][0].'" alt="'.$header_slider['alt'].'" /></div>';
                 } ?>
              </div>
            </div>
             <?php endwhile; ?>

        <?php else : ?>

            <?php get_template_part( 'template-parts/content', 'none' ); ?>

        <?php endif; ?>

    </main><!-- #main -->
</div><!-- #content-full -->

<?php get_footer(); ?>
