<?php
/**
 * Template Name: Home page
 *
 * Template for pages
 *
 * @package      responsive_mobile
 * @license      license.txt
 * @copyright    2014 CyberChimps Inc
 * @since        0.0.1
 *
 * Please do not edit this file. This file is part of the responsive_mobile Framework and all modifications
 * should be made in a child theme.
 */

// If this file is called directly, abort.
if ( ! defined( 'WPINC' ) ) {
    die;
}

get_header(); ?>

<div id="content-full" class="content-area">
    <main id="main" class="site-main full-width" role="main">

        <?php if ( have_posts() ) : ?>

            <?php get_template_part( 'template-parts/loop-header' ); ?>

            <?php /* Start the Loop */ ?>
            <?php while ( have_posts() ) : the_post(); ?>

                <?php
                $header_bg_1 = image_details(CFS()->get( 'background_image_1' ));
                $header_bg_2 = image_details(CFS()->get( 'background_image_2' ));
                $header_bg_3 = image_details(CFS()->get( 'background_image_3' ));
                $header_bg_4 = image_details(CFS()->get( 'background_image_4' ));
                $header_slider_array = [$header_bg_1, $header_bg_2, $header_bg_3, $header_bg_4];
                $header_logo = image_details(CFS()->get( 'header_logo'));
                $header_text = CFS()->get( 'header_text');
                $header_logo_display = CFS()->get( 'header_logo_display');
                ?>
                <div class="main-banner-section">
                    <div class="slider">
                        <?php foreach ($header_slider_array as $header_slider) {
                            if (!empty($header_slider['url'][0])) {
                                echo '<div class="slide"><img src="' . $header_slider['url'][0] . '" alt="' . $header_slider['alt'] . '" /></div>';
                            }
                        } ?>
                    </div>
                    <div class="banner-secction-text">
                        <div class="container">
                            <div class="banner-secction-text-inner">
                                <?php if ($header_logo_display == 1 && $header_logo) {
                                    echo '<img src="'.$header_logo['url'][0].'"/>';
                                }
                                if ($header_text) {
                                    echo '<h3>'.$header_text.'</h3>';
                                }
                                ?>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="container">
                <?php get_template_part( 'template-parts/content', 'page' ); ?>
                <?php
                $map_title = CFS()->get( 'map_title');
                $adress = CFS()->get( 'adress');
                $address = str_replace(" ", "+", $adress);
                $json = file_get_contents("https://maps.google.com/maps/api/geocode/json?address=$address&sensor=false&key=AIzaSyD8-rVs3O2zB33Yx83-DvHIn09JsGshQQM");
                $json = json_decode($json);
                $lat = $json->{'results'}[0]->{'geometry'}->{'location'}->{'lat'};
                $long = $json->{'results'}[0]->{'geometry'}->{'location'}->{'lng'};
                ?>
                    <input type="hidden" value="<?php echo $lat;?>" id="lat">
                    <input type="hidden" value="<?php echo $long;?>" id="long">
                    <h2 class="map-title"><?php echo $map_title; ?></h2>
                    <div class="map-container">
                        <div id="map"></div>
                    </div>
                </div>
             <?php endwhile; ?>

        <?php else : ?>

            <?php get_template_part( 'template-parts/content', 'none' ); ?>

        <?php endif; ?>

    </main><!-- #main -->
</div><!-- #content-full -->

<?php get_footer(); ?>
<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyD8-rVs3O2zB33Yx83-DvHIn09JsGshQQM&callback=initMap&v=weekly" defer
></script>
<script>
    let map;
    var lat=document.getElementById("lat").value;
    var long=document.getElementById("long").value;
    function initMap() {
        const myLatLng = { lat: parseFloat(lat), lng: parseFloat(long) };
        const mapOptions = {
            zoom: 16,
            center: myLatLng,
        };

        map = new google.maps.Map(document.getElementById("map"), mapOptions);
        const marker = new google.maps.Marker({
            position: myLatLng,
            title: 'Alphaclinic Zurich',
            map: map,
        });
    }
    window.initMap = initMap;
</script>
