<?php
/**
 * Template Name: Footer
 *
 * Template for pages
 *
 * @package      responsive_mobile
 * @license      license.txt
 * @copyright    2014 CyberChimps Inc
 * @since        0.0.1
 *
 * Please do not edit this file. This file is part of the responsive_mobile Framework and all modifications
 * should be made in a child theme.
 */

$footer_logo = image_details(CFS()->get( 'footer_logo', 131 ));
$footer_submenu = CFS()->get( 'footer_submenu', 131 );
$footer_adress = CFS()->get( 'footer_adress', 131 );
$footer_button = CFS()->get( 'footer_button', 131 );
$twitter = CFS()->get( 'twitter', 131 );
$instagram = CFS()->get( 'instagram', 131 );
$facebook = CFS()->get( 'facebook', 131 );
$youtube = CFS()->get( 'youtube', 131 );
?>
<div class="container">
<div class="footer-section">
    
        <div class="footer-column-1">
            <img src="<?php echo $footer_logo['url'][0]; ?>" alt="<?php echo $footer_logo['alt']; ?>">
        </div>
        <div class="footer-right-section">
            <div class="footer-column-2">
                <ul>
                    <?php foreach ($footer_submenu as $slug => $submenu) {
                    echo '<li><a href="'.$slug.'">'.$submenu.'</a></li>';
                    } ?>
                </ul>
            </div>

            <div class="footer-column-3">
                <?php echo '<div class="footer-addresss">'.$footer_adress.'</div>';?>
            </div>

            <div class="footer-column-4">
                <?php echo '<div class="footer-kontakt">'.$footer_button.'</div>';?>
            </div>

            <div class="footer-column-5">
                <div class="footer-social-icons">
                <?php if ($twitter) {
                    echo '<a href="'.$twitter.'"><img src="'.get_template_directory_uri().'/images/twitter.webp"/></a>';
                }
                if ($instagram) {
                    echo '<a href="'.$instagram.'"><img src="'.get_template_directory_uri().'/images/instagram.webp"/></em></a>';
                }
                if ($facebook) {
                    echo '<a href="'.$facebook.'"><img src="'.get_template_directory_uri().'/images/facebook.webp"/></a>';
                }
                if ($youtube) {
                    echo '<a href="'.$youtube.'"><img src="'.get_template_directory_uri().'/images/youtube.webp"/></a>';
                }?>
                </div>
            </div>
        </div>
    </div>

</div>
